project:
  type: website
  output-dir: _site

website:
  title: "Reaction Engineering Basics, The Course"
  favicon: graphics/BuffaloBadger_16_16.png
  search:
    location: navbar
    type: overlay
  navbar:
    title: false
    search: true
    logo: graphics/Banner.png
    left:
      - text: "REB, The Book"
        href: http://buffalobadger.github.io/RE_Basics
      - text: "REB, The Course"
        href: http://buffalobadger.github.io/RE_Basics_Course
      - text: "REB, The Design"
        href: http://buffalobadger.github.io/RE_Basics_Design
      - text: "The Sett"
        href: http://buffalobadger.github.io/The_Sett
      - text: "About"
        href: http://buffalobadger.github.io/about.html
  sidebar:
    style: floating
    search: false
    collapse-level: 1
    contents:
      - text: "Welcome"
        href: index.qmd
      - section: "*Getting Started*"
        contents:
          - text: "Preparing for the Course"
            href: preparing.qmd
          - text: "Taking the Course"
            href: taking.qmd
      - text: "Class 1: Reaction Engineering, Ethics, and Safety"
        href: classes/class_1.qmd
      - section: "*Reactions, Rates, and Rate Expressions*"
        contents:
          - text: "Class 2: Reactions and Stoichiometry"
            href: classes/class_2.qmd
          - text: "Class 3: Rates and Rate Expressions"
            href: classes/class_3.qmd
          - text: "Class 4: The Bodenstein Steady-State Approximation"
            href: classes/class_4.qmd
          - text: "Class 5: Rate-Determining Steps and Quasi-Equilibrium"
            href: classes/class_5.qmd
          - text: "Class 6: Conservation of Catalyst and Charge"
            href: classes/class_6.qmd
          - text: "Class 7: Most Abundant Intermediate"
            href: classes/class_7.qmd
      - text: "Class 8: Qualitative and Quantitative Analysis of Ideal Reactors"
        href: classes/class_8.qmd
      - section: "*CSTR Analysis*"
        contents:
          - text: "Class 9: Non-Isothermal, Steady-State CSTR Analysis"
            href: classes/class_9.qmd
          - text: "Class 10: Selectivity in Steady-State CSTRs"
            href: classes/class_10.qmd
          - text: "Class 11: Multiplicity of CSTR Steady States"
            href: classes/class_11.qmd
          - text: "Class 12: CSTR Startup and Shut Down"
            href: classes/class_12.qmd
          - text: "Class 13: Stability of CSTR Steady States"
            href: classes/class_13.qmd
      - section: "*BSTR Analysis*"
        contents:
          - text: "Class 14: Non-Isothermal BSTR Analysis"
            href: classes/class_14.qmd
          - text: "Class 15: BSTR Properties and Initial Values"
            href: classes/class_15.qmd
          - text: "Class 16: Net Production Rate"
            href: classes/class_16.qmd
          - text: "Class 17: Selectivity in BSTRs"
            href: classes/class_17.qmd
          - text: "Class 18: Variable BSTR Heating or Cooling"
            href: classes/class_18.qmd
      - section: "*SBSTR Analysis*"
        contents:
          - text: "Class 19: Use of SBSTRs to Control Temperature"
            href: classes/class_19.qmd
          - text: "Class 20: Selectivity in SBSTRs"
            href: classes/class_20.qmd
      - section: "*PFR Analysis*"
        contents:
          - text: "Class 21: Non-Isothermal, Steady-State PFR Analysis"
            href: classes/class_21.qmd
          - text: "Class 22: Pressure Drop in Steady-State PFRs"
            href: classes/class_22.qmd
          - text: "Class 23: Steady-State Packed Bed PFRs"
            href: classes/class_23.qmd
      - text: "Class 24: Design of Ideal Reactors"
        href: classes/class_24.qmd
      - section: "*Kinetics Data Analysis*"
        contents:
          - text: "Class 25: Kinetics Experiments and Data Generation"
            href: classes/class_25.qmd
          - text: "Class 26: Analysis of CSTR Kinetics Data"
            href: classes/class_26.qmd
          - text: "Class 27: Analysis of BSTR Kinetics Data"
            href: classes/class_27.qmd
          - text: "Class 28: Analysis of PFR Kinetics Data"
            href: classes/class_28.qmd
          - text: "Class 29: Differential and Linearized Model Data Analysis"
            href: classes/class_29.qmd
      - section: "*Reactor System Analysis*"
        contents:
          - text: "Class 30: Analysis of Steady-State Flow Reactor Systems"
            href: classes/class_30.qmd
          - text: "Class 31: Analysis of Steady-State, Thermally Back-Mixed PFRs"
            href: classes/class_31.qmd
          - text: "Class 32: Analysis of Steady-State, Recycle PFRs"
            href: classes/class_32.qmd
      - section: "*Non-Ideal Reactor Models*"
        contents:
          - text: "Class 33: The Age Function from Step-Change Stimuli"
            href: classes/class_33.qmd
          - text: "Class 34: The Age Function from Impulse Stimuli"
            href: classes/class_34.qmd
          - text: "Class 35: An Early Mixing Segregated Flow Reactor Model"
            href: classes/class_35.qmd
          - text: "Class 36: A Late Mixing Segregated Flow Reactor Model"
            href: classes/class_36.qmd
          - text: "Class 37: An Empirical Axial Dispersion Reactor Model"
            href: classes/class_37.qmd
          - text: "Class 38: Zoned Reactor Models"
            href: classes/class_38.qmd
      - text: "Class 39: Intermediate Reaction Engineering"
        href: classes/class_39.qmd
      - section: "*Collected Resources*"
        contents:
        - text: "Examples by Class"
          href: catalog.qmd
        - text: "Numerical Methods Videos"
          href: nm_videos.qmd


bibliography: references.bib

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: false



