project:
  type: website
  output-dir: _site

website:
  title: "Reaction Engineering Basics, The Course"
  favicon: graphics/BuffaloBadger_16_16.png
  search:
    location: navbar
    type: overlay
  navbar:
    title: false
    search: true
    left:
      - text: "![](graphics/REB_Book_Logo.png){height=48px fig-alt='REB The Book'}"
        href: http://buffalobadger.github.io/RE_Basics
      - text: "![](graphics/REB_Slide_Logo.png){height=48px fig-alt='REB The Course'}"
        href: http://buffalobadger.github.io/SCoRE
      - text: "![](graphics/REB_About_Logo.png){height=48px fig-alt='About REB'}"
        href: about.qmd
  sidebar:
    style: floating
    search: false
    collapse-level: 1
    contents:
      - text: "Welcome"
        href: index.qmd
      - section: "Getting Started"
        href: getting_started.qmd
        contents:
          - text: "Preparing for the Course"
            href: preparing.qmd
          - text: "Taking the Course"
            href: taking.qmd
      - section: "Introduction and Review"
        href: introduction.qmd
        contents:
          - text: "Class 1: Reaction Engineering, Ethics, and Safety"
            href: class_1.qmd
          - text: "Class 2: Reactions and Stoichiometry"
            href: class_2.qmd
      - section: "Rates and Rate Expressions"
        href: rate_expressions.qmd
        contents:
          - text: "Class 3: Rates and Rate Expressions"
            href: class_3.qmd
      - section: "Numerical Methods Supplement"
        href: numerical_methods.qmd
        contents:
          - text: "Linear Least Squares"
            href: linear_least_squares.qmd

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: false



